# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b60ae1908a76db1ae7d25d36dd0aa9c49e5981fae4f2a943d2ef877d9c542a5d1dd9a281906b03f4863380cfe1540f07953bcbaa674a9fd9e5e996307e1ae2bc

test:
  secret_key_base: edfce1e642433e0fc2f87d84080a838a27ca2069351931c1d8c11eeb11b1185175f99179680d81fb56c48a9d34166e2dd9ad3bed78b882cdb2fb598dbc76a81d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
